### PR TITLE
feat: add some helpers for determining branch body size

### PR DESCRIPTION
**Pull request by rphmeier**

### CODE REVIEW

**Comment by rphmeier** [comment]
* **#32** <a href="https://app.graphite.dev/github/pr/thrumdev/bitbox/32?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2  dependent PRs ([#33](https://github.com/thrumdev/bitbox/pull/33) <a href="https://app.graphite.dev/github/pr/thrumdev/bitbox/33?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#35](https://github.com/thrumdev/bitbox/pull/35) <a href="https://app.graphite.dev/github/pr/thrumdev/bitbox/35?utm_source=stack-comment-icon" target="_blank">Graphite</a>) 👈
* **#31** <a href="https://app.graphite.dev/github/pr/thrumdev/bitbox/31?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @rphmeier and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by pepyakin — COMMENTED** [review]
I was not able to find, where this was used. Is this even used?

**Comment by rphmeier** [comment]
It's not used (though I added it before implementing `OrdMap` in which case it would be used)

However, it's absolutely necessary for the `update` logic, as we use this to determine whether to perform splits/merges

**Comment by rphmeier** [comment]
### Merge activity

* **Jul 22, 12:57 PM EDT**: @rphmeier started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/thrumdev/bitbox/32).
* **Jul 22, 1:00 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/thrumdev/bitbox/32) rebased this pull request as part of a merge.
* **Jul 22, 1:01 PM EDT**: @rphmeier merged this pull request with [Graphite](https://app.graphite.dev/github/pr/thrumdev/bitbox/32).

**Pull request merged**
